In [1]:
import numpy as np
import pandas as pd
from numpy.linalg import eig
from numpy.linalg import svd
from numpy.linalg import qr
from sklearn.metrics import mean_squared_error

## PCA using covariance matrix

In [2]:
#covariance
x = [45,37,42,35,39]
y = [38,31,26,28,33]
z = [10,15,17,21,12]
data = np.array([x,y,z])
print(f'data.shape {data.shape}')
print(data)

data.shape (3, 5)
[[45 37 42 35 39]
 [38 31 26 28 33]
 [10 15 17 21 12]]


In [3]:
# define a matrix
A = data
print(f'A.shape {A.shape}')
# calculate the mean of each row
M = np.mean(A, axis=1)
print(f'M.shape {M.shape}')
# center columns by subtracting column means
C = A.T - M
print(f'C.shape {C.shape}')
# calculate covariance matrix of centered matrix
V = A.dot(A.T)/(A.shape[0]-1)
print(V.shape)
#eigendecomposition of covariance matrix
values, vectors = eig(V)
print(f'Eigen vectors {vectors.shape}')

# project data
k = 2
P = vectors[:,0:k].T.dot(C.T)
print(f'Principal Component {P.shape}')
A_estimate = vectors[:,0:k].dot(P)
print(f'A_estimate {A_estimate.shape}')
print((A_estimate.T + M).T)

A.shape (3, 5)
M.shape (3,)
C.shape (5, 3)
(3, 3)
Eigen vectors (3, 3)
Principal Component (2, 5)
A_estimate (3, 5)
[[44.8764548  37.00207673 42.06499339 35.11406186 38.94241323]
 [34.96690144 31.05098469 27.59562124 30.8002777  31.58621493]
 [16.78103539 14.88601459 13.43270278 14.73947736 15.16076988]]


In [4]:
# define a matrix
A = data
print(f'A.shape {A.shape}')
# calculate the mean of each row
M = np.mean(A, axis=1)
print(f'M.shape {M.shape}')
# center columns by subtracting column means
C = A.T - M
print(f'C.shape {C.shape}')
# calculate covariance matrix of centered matrix
V = np.cov(C.T)
print(V.shape)
#eigendecomposition of covariance matrix
values, vectors = eig(V)
print(f'Eigen vectors {vectors.shape}')

# project data
k = 3
P = vectors[:,0:k].T.dot(C.T)
print(f'Principal Component {P.shape}')
A_estimate = vectors[:,0:k].dot(P)
print((A_estimate.T + M).T)

A.shape (3, 5)
M.shape (3,)
C.shape (5, 3)
(3, 3)
Eigen vectors (3, 3)
Principal Component (3, 5)
[[45. 37. 42. 35. 39.]
 [38. 31. 26. 28. 33.]
 [10. 15. 17. 21. 12.]]


In [5]:
# define a matrix
A = data.T
print(f'A.shape {A.shape}')
# calculate the mean of each column
M = np.mean(A, axis=0)
print(f'M.shape {M.shape}')
# center columns by subtracting column means
C = A - M
print(f'C.shape {C.shape}')
# calculate covariance matrix of centered matrix
V = np.cov(C.T)
print(V.shape)
#eigendecomposition of covariance matrix
values, vectors = eig(V)
print(f'Eigen vectors {vectors.shape}')

# project data
k = 3
P = vectors[:,0:k].T.dot(C.T)
print(f'Principal Component {P.shape}')
A_estimate = vectors[:,0:k].dot(P)
print((A_estimate.T + M).T)

A.shape (5, 3)
M.shape (3,)
C.shape (5, 3)
(3, 3)
Eigen vectors (3, 3)
Principal Component (3, 5)
[[45. 37. 42. 35. 39.]
 [38. 31. 26. 28. 33.]
 [10. 15. 17. 21. 12.]]


In [6]:
def pca_reconstruction(cov, C, variance_explained=1):
    eig_values, eig_vectors = eig(cov)
    k = len(eig_values)
    if variance_explained != 1:
        trace = sum(eig_values)
        var_explained = 0
        for i, val in enumerate(eig_values):
            var_explained += val/trace
            print(f'{i} - {var_explained}')
            if var_explained >= variance_explained:
                k = i
    Y = eig_vectors[:,0:k].T.dot(C.T)
    C_estimate = eig_vectors[:,0:k].dot(Y)
    return C_estimate

In [7]:
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
print(X)
M = np.mean(X, axis=0)
C = X - M
cov = np.cov(C.T)
C_estimate = pca_reconstruction(cov, C, variance_explained=1)
X_estimate = C_estimate.T + M
X_estimate

[[-1 -1]
 [-2 -1]
 [-3 -2]
 [ 1  1]
 [ 2  1]
 [ 3  2]]


array([[-1., -1.],
       [-2., -1.],
       [-3., -2.],
       [ 1.,  1.],
       [ 2.,  1.],
       [ 3.,  2.]])

In [8]:
C_estimate = pca_reconstruction(cov, C, variance_explained=0.9)
X_estimate = C_estimate.T + M
X_estimate

0 - 0.9924428900898052
1 - 1.0


array([[-1.15997501, -0.75383654],
       [-1.86304424, -1.21074232],
       [-3.02301925, -1.96457886],
       [ 1.15997501,  0.75383654],
       [ 1.86304424,  1.21074232],
       [ 3.02301925,  1.96457886]])

## PCA using SVD

In [9]:
U, S, Vt = np.linalg.svd(data, full_matrices=False)
print(f'data.shape {data.shape}')
print(f'U.shape {U.shape}')
print(f'S.shape {S.shape}')
print(f'V.shape {V.shape}')

data.shape (3, 5)
U.shape (3, 3)
S.shape (3,)
V.shape (3, 3)


In [10]:
print(data)
print(f'data from svd{np.dot(U*S, Vt)}')

[[45 37 42 35 39]
 [38 31 26 28 33]
 [10 15 17 21 12]]
data from svd[[45. 37. 42. 35. 39.]
 [38. 31. 26. 28. 33.]
 [10. 15. 17. 21. 12.]]


In [11]:
k = 2
data_estimate = np.dot(U[:,0:k]*S[0:k], Vt[0:k, :])
data_estimate

array([[44.81347318, 38.06162501, 39.01822428, 36.73429164, 39.52092306],
       [38.19652839, 29.88145062, 29.14165864, 26.17271558, 32.45114502],
       [10.08450708, 14.51902451, 18.35091114, 20.21426891, 11.76399272]])

In [12]:
def svd_reconstruction(U, S, Vt, variance_explained=1):
    if variance_explained == 1:
        A_estimate = np.dot(U*S, Vt)
    else:
        var_explained = 0
        trace = sum(S)
        for i, val in enumerate(S):
            var_explained += val/trace
            if var_explained >= variance_explained:
                k = i
        A_estimate = np.dot(U[:,0:k]*S[0:k], Vt[0:k, :])
    return A_estimate

In [13]:
print(svd_reconstruction(U, S, Vt, variance_explained=1))

[[45. 37. 42. 35. 39.]
 [38. 31. 26. 28. 33.]
 [10. 15. 17. 21. 12.]]


In [14]:
print(svd_reconstruction(U, S, Vt, variance_explained=0.9))

[[44.81347318 38.06162501 39.01822428 36.73429164 39.52092306]
 [38.19652839 29.88145062 29.14165864 26.17271558 32.45114502]
 [10.08450708 14.51902451 18.35091114 20.21426891 11.76399272]]


## INCREMENTAL PCA

In [15]:
def incremental_pca(U, S, npoints, acc_mean, new_matrix):
    new_matrix_mean = np.mean(new_matrix, axis=1)
    Best = (new_matrix.T - new_matrix_mean).T * np.sqrt((npoints + new_matrix.shape[1])/(npoints * new_matrix.shape[1]))* (new_matrix_mean - acc_mean)  
    acc_mean = (npoints/(npoints + new_matrix.shape[1])) * acc_mean + (new_matrix.shape[1]/(npoints + new_matrix.shape[1]))*new_matrix_mean

In [16]:
A = data
print(f'A \n{A}')
print(f'A.shape {A.shape}')
print(f'U.shape {U.shape}')
print(f'S.shape {S.shape}')
print(f'V.shape {V.shape}')

x = [40, 38, 42, 39]
y = [39, 28, 23, 25]
z = [11, 12, 13, 15]
B = np.array([x,y,z])

acc_mean = np.mean(A, axis=1)
print(f'acc_mean \n{acc_mean}')
print(f'B \n{B}')
print(f'B.shape {B.shape}')
new_matrix_mean = np.mean(B, axis=1)
print(f'new_matrix_mean.shape {new_matrix_mean.shape}')
print(f'new_matrix_mean \n{new_matrix_mean}')

npoints = A.shape[1]
Best = (B.T - new_matrix_mean) * np.sqrt((npoints + B.shape[1])/(npoints * B.shape[1])) * (new_matrix_mean - acc_mean)
Best = Best.T
print(f'Best \n{Best}')
print(f'Best.shape {Best.shape}')

q, r = qr(Best - np.dot(np.dot(U, U.T), Best))
print(f'q \n{q.shape}')
print(f'r \n{r.shape}')

A 
[[45 37 42 35 39]
 [38 31 26 28 33]
 [10 15 17 21 12]]
A.shape (3, 5)
U.shape (3, 3)
S.shape (3,)
V.shape (3, 3)
acc_mean 
[39.6 31.2 15. ]
B 
[[40 38 42 39]
 [39 28 23 25]
 [11 12 13 15]]
B.shape (3, 4)
new_matrix_mean.shape (3,)
new_matrix_mean 
[39.75 28.75 12.75]
Best 
[[  0.02515576  -0.17609035   0.22640188  -0.07546729]
 [-16.84597713   1.23263247   9.45018229   6.16316236]
 [  2.6413553    1.13200941  -0.37733647  -3.39602824]]
Best.shape (3, 4)
q 
(3, 3)
r 
(3, 4)


In [17]:
from sklearn.decomposition import PCA, IncrementalPCA
rng = np.random.RandomState(0)
A = rng.randn(5, 3) + 2
B = rng.randn(7, 3) + 5

print(f'A.shape {A.shape}')
print(f'A \n{A}')

pca = IncrementalPCA()
pca.partial_fit(A)
print(f'pca.singular_values_ \n{pca.singular_values_}')
print(f'pca.components_ {pca.components_}')
print(f'pca.explained_variance_ {pca.explained_variance_}')
print(f'pca.explained_variance_ratio_ {pca.explained_variance_ratio_}')
print(f'pca.n_samples_seen_ {pca.n_samples_seen_}')

print(f'B.shape {B.shape}')
print(f'B \n{B}')
pca.partial_fit(B)
print(f'pca.singular_values_ \n{pca.singular_values_}')
print(f'pca.components_ {pca.components_}')
print(f'pca.explained_variance_ {pca.explained_variance_}')
print(f'pca.explained_variance_ratio_ {pca.explained_variance_ratio_}')
print(f'pca.n_samples_seen_ {pca.n_samples_seen_}')

C = np.vstack((A,B))
print('C reconstruction')
print(f'{pca.inverse_transform(C)}')

A.shape (5, 3)
A 
[[3.76405235 2.40015721 2.97873798]
 [4.2408932  3.86755799 1.02272212]
 [2.95008842 1.84864279 1.89678115]
 [2.4105985  2.14404357 3.45427351]
 [2.76103773 2.12167502 2.44386323]]
pca.singular_values_ 
[2.59757554 1.11936464 0.66182766]
pca.components_ [[-0.51356804 -0.55749392  0.65226405]
 [ 0.46282974  0.46011835  0.75768049]
 [ 0.72252093 -0.69100769 -0.02172268]]
pca.explained_variance_ [1.68684967 0.3132443  0.10950396]
pca.explained_variance_ratio_ [0.79960719 0.14848531 0.0519075 ]
pca.n_samples_seen_ 5
B.shape (7, 3)
B 
[[5.33367433 6.49407907 4.79484174]
 [5.3130677  4.14590426 2.44701018]
 [5.6536186  5.8644362  4.25783498]
 [7.26975462 3.54563433 5.04575852]
 [4.81281615 6.53277921 6.46935877]
 [5.15494743 5.37816252 4.11221425]
 [3.01920353 4.65208785 5.15634897]]
pca.singular_values_ 
[7.7034119  3.90541681 2.98650435]
pca.components_ [[ 0.45437679  0.68754006  0.56641893]
 [ 0.79520316 -0.02647888 -0.60576465]
 [-0.40148933  0.72566351 -0.55876541]]
pc

In [18]:
# Test that fit and partial_fit get equivalent results.
rng = np.random.RandomState(1999)
n, p = 50, 3
X = rng.randn(n, p)  # spherical data
X[:, 1] *= .00001  # make middle component relatively small
X += [5, 4, 3]  # make a large mean

# same check that we can find the original data from the transformed
# signal (since the data is almost of rank n_components)
batch_size = 10
ipca = IncrementalPCA(n_components=2, batch_size=batch_size).fit(X)
pipca = IncrementalPCA(n_components=2, batch_size=batch_size)
# Add one to make sure endpoint is included
batch_itr = np.arange(0, n + 1, batch_size)
for i, j in zip(batch_itr[:-1], batch_itr[1:]):
    pipca.partial_fit(X[i:j, :])

In [19]:
ipca.components_

array([[ 7.61191039e-01, -4.92468531e-07,  6.48527719e-01],
       [-6.48527719e-01, -2.06078051e-06,  7.61191039e-01]])

In [20]:
pipca.components_

array([[ 7.61191039e-01, -4.92468531e-07,  6.48527719e-01],
       [-6.48527719e-01, -2.06078051e-06,  7.61191039e-01]])

In [21]:
from sklearn.decomposition import PCA, IncrementalPCA
rng = np.random.RandomState(0)
A = rng.randn(5, 3) + 2
B = rng.randn(7, 3) + 5

print(f'A.shape {A.shape}')
print(f'A \n{A}')

pca = IncrementalPCA(n_components=2)
pca.partial_fit(A)
print(f'pca.singular_values_ \n{pca.singular_values_}')
print(f'pca.components_ {pca.components_}')
print(f'pca.explained_variance_ {pca.explained_variance_}')
print(f'pca.explained_variance_ratio_ {pca.explained_variance_ratio_}')
print(f'pca.n_samples_seen_ {pca.n_samples_seen_}')

##a is the projection of A in k dimension
##a: ndarray of shape (n_samples, n_components)
a = pca.transform(A)
print(f'a.shape {a.shape}')
print(f'a \n{a}')
print('A reconstruction')
print(f'{pca.inverse_transform(a)}')

A.shape (5, 3)
A 
[[3.76405235 2.40015721 2.97873798]
 [4.2408932  3.86755799 1.02272212]
 [2.95008842 1.84864279 1.89678115]
 [2.4105985  2.14404357 3.45427351]
 [2.76103773 2.12167502 2.44386323]]
pca.singular_values_ 
[2.59757554 1.11936464]
pca.components_ [[-0.51356804 -0.55749392  0.65226405]
 [ 0.46282974  0.46011835  0.75768049]]
pca.explained_variance_ [1.68684967 0.3132443 ]
pca.explained_variance_ratio_ [0.79960719 0.14848531]
pca.n_samples_seen_ 5
a.shape (5, 2)
a 
[[ 0.16989797  0.68360167]
 [-2.1688981   0.09744077]
 [ 0.18966821 -0.76666454]
 [ 1.31794514  0.29964437]
 [ 0.49138678 -0.31402227]]
A reconstruction
[[3.45447105 2.6962359  2.98804559]
 [4.38430928 3.7303971  1.0184103 ]
 [2.77309135 2.01792001 1.90210259]
 [2.68716386 1.8795408  3.44595853]
 [2.82763464 2.05798277 2.44186099]]


In [22]:
def reconstruct_incremental_pca(X, pca, variance_explained=0.9):
    pca.partial_fit(X)
    #Y is the projection of X on k dimension
    Y = pca.transform(X)
    k = 1
    # check how many principal components we need based on the explained variance
    if variance_explained != 1:
        var_explained = 0
        for i, val in enumerate(pca.explained_variance_ratio_):
            var_explained += val
            if var_explained >= variance_explained:
                k = i
    # to reconstruct X, we use the formula X=YW
    X_estimate = np.dot(Y[:,0:k],pca.components_[0:k,:]) + np.mean(X, axis=0)
    return(X_estimate)

In [23]:
A = rng.randn(5, 3) + 2
print(f'A.shape {A.shape}')
print(f'A \n{A}')
pca = IncrementalPCA()
A_estimate = reconstruct_incremental_pca(A, pca, variance_explained=0.9)
print(f'A_estimate \n{A_estimate}')

A.shape (5, 3)
A 
[[3.23029068 3.20237985 1.61267318]
 [1.69769725 0.95144703 0.57998206]
 [0.29372981 3.9507754  1.49034782]
 [1.5619257  0.74720464 2.77749036]
 [0.38610215 1.78725972 1.10453344]]
A_estimate 
[[3.21132916 3.21086153 1.72715355]
 [1.52710463 1.02775484 1.60993654]
 [0.34203728 3.92916698 1.19869105]
 [1.74488744 0.665364   1.67285718]
 [0.34438709 1.80591929 1.35638854]]


## SPIRIT

In [24]:
n = 3
k = 3
W = np.zeros((n,k))
W[0,0] = 1
print
d = 0.01 *np.ones(n)
lamda =1

In [25]:
k = 3
xt = A[0,:]
print(f'xt.shape {xt.shape}')
for i in range(k):
    yi = np.dot(W[:,i].T, xt)
    print(f'yi.shape {yi.shape}')
    d[i] = lamda*d[i] + yi
    print(f'W[:,i].shape{W[:,i].shape}')
    e = xt - (yi*W[:,i])
    print(f'e.shape {e.shape}')
    W[:,i] = W[:,i] + (1/d[i])*yi*e
    xt = xt - yi*W[:,i]

xt.shape (3,)
yi.shape ()
W[:,i].shape(3,)
e.shape (3,)
yi.shape ()
W[:,i].shape(3,)
e.shape (3,)
yi.shape ()
W[:,i].shape(3,)
e.shape (3,)


In [87]:
def track_W(xt, W, d, k, lamda=1):
    if W is None:
        W = np.zeros((xt.shape[0], xt.shape[0]))
        np.fill_diagonal(W, W.diagonal() + 1)
        d = 0.01 * np.ones(xt.shape[0])
    x = xt.copy()
    Yt = np.zeros(xt.shape[0])
    for i in range(k):
        yi = np.dot(W[:,i].T, x)
        d[i] = lamda*d[i] + yi**2
        e = x - (yi*W[:,i])
        W[:,i] = W[:,i] + (1/d[i])*yi*e
        x = x - yi*W[:,i]
        Yt[i] = yi
    return W, d, Yt

In [88]:
xt = A[0,:]
t= 1
W = None
d = None
k = 1
lamda =1
W, d, Yt = track_W(xt, W, d, k, lamda=1)
E_est = np.zeros(xt.shape[0])
E = 0

In [89]:
def spirit_algorithm(xt, t, E, E_est, W, d, k, lamda=1, fE=0.95, FE=0.98):
    W, d, Yt = track_W(xt, W, d, k, lamda)
    E = (lamda*(t-1)*E + np.sum(xt**2)) / t
    print(f'E {E}')
    E_est[0:k] = (lamda*(t-1)*E_est[0:k] + Yt[0:k]**2)/t
    E_k = np.sum(E_est[0:k])
    print(f'E_k {E_k}')
    print(f'(fE*E) {(fE*E)}')
    print(f'(FE*E) {(FE*E)}')
    if E_k < (fE*E):
        k = k + 1
        print('Update k = k+1')
        spirit_algorithm(xt, t, E, E_est, W, d, k, lamda, fE=0.95, FE=0.98)
    elif E_k > (FE*E):
        k = k - 1
    return E, E_est, W, d, k
    

In [90]:
xt = A[0,:]
t= 1
W = None
d = None
k = 1
lamda =1
E_est = np.zeros(xt.shape[0])
E = 0
spirit_algorithm(xt, t, E, E_est, W, d, k, lamda, fE=0.95, FE=0.98)

E 23.290729371748398
E_k 10.43477788199636
(fE*E) 22.126192903160977
(FE*E) 22.824914784313428
Update k = k+1
E 23.290729371748398
E_k 52.36478632209681
(fE*E) 22.126192903160977
(FE*E) 22.824914784313428


(23.290729371748398,
 array([51.93065771,  0.43412862,  0.        ]),
 array([[0.54064871, 0.98771736, 0.        ],
        [0.53581838, 1.        , 0.        ],
        [0.26983056, 0.49224711, 1.        ]]),
 array([6.23754356e+01, 4.44128616e-01, 1.00000000e-02]),
 2)