In [1]:
import numpy as np
import pandas as pd
from numpy.linalg import eig

In [2]:
#covariance
A = [45,37,42,35,39]
B = [38,31,26,28,33]
C = [10,15,17,21,12]

data = np.array([A,B,C])

In [8]:
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
print(f'X {X.shape}')
# define a matrix
A = data.T
# calculate the mean of each column
M = np.mean(A, axis=0)
print(f'M.shape {M.shape}')
# center columns by subtracting column means
C = A - M
print(f'C.shape {C.shape}')
# calculate covariance matrix of centered matrix
V = np.cov(C.T)
print(V.shape)
#eigendecomposition of covariance matrix
values, vectors = eig(V)
print(f'Eigen vectors {vectors.shape}')

# project data
k = 2
P = vectors[:,0:k].T.dot(C.T)
print(f'Principal Component {P.shape}')
A_estimate = vectors[:,0:k].dot(P)
print((A_estimate.T + M).T)

X (6, 2)
M.shape (3,)
C.shape (5, 3)
(3, 3)
Eigen vectors (3, 3)
Principal Component (2, 5)
[[44.569391   37.281906   42.14752752 34.5138843  39.48729118]
 [37.25309646 31.48897395 26.25589068 27.15681853 33.84522038]
 [ 8.90681984 15.71567022 17.37452576 19.76590588 13.2370783 ]]


In [4]:
M

array([39.6, 31.2, 15. ])