In [1]:
import numpy as np
from sklearn.decomposition import IncrementalPCA
from sklearn.metrics import mean_squared_error

In [2]:
def reconstruct_incremental_pca(X, pca, variance_explained=0.9025):
    pca.partial_fit(X)
    #Y is the projection of X on k dimension
    Y = pca.transform(X)
    k = 1
    # check how many principal components we need based on the explained variance
    if variance_explained != 1:
        var_explained = 0
        for i, val in enumerate(pca.explained_variance_ratio_):
            var_explained += val
            if var_explained >= variance_explained:
                k = i
    # to reconstruct X, we use the formula X=YW
    X_estimate = np.dot(Y[:,0:k],pca.components_[0:k,:]) + np.mean(X, axis=0)
    return(X_estimate)

In [3]:
## generate 3 dimension data set of 10 points
np.random.seed(1)
rng = np.random.RandomState(1999)
A = rng.randn(10, 3) + 2
print('A')
print(A)
pca = IncrementalPCA()
A_estimate = reconstruct_incremental_pca(A, pca, variance_explained=0.9025)
print('A_estimate')
print(A_estimate)

A
[[1.68251986 2.69206233 0.71562236]
 [2.39334583 2.21180288 1.58854318]
 [2.94547341 2.90643341 1.45884194]
 [3.20463807 1.92962428 2.70887691]
 [0.96984499 1.03195449 3.3538902 ]
 [2.80426695 1.64460456 1.19536682]
 [2.2470435  1.8595206  1.9274096 ]
 [0.68802366 0.16304126 1.75841876]
 [1.16916187 0.6220643  1.90347192]
 [2.09439562 1.49333031 2.62422045]]
A_estimate
[[2.04434785 2.26673938 0.53477461]
 [2.43633006 2.16127561 1.56705894]
 [3.06429519 2.76676034 1.39945281]
 [3.02607211 2.13952568 2.7981272 ]
 [1.36203339 0.57094337 3.1578678 ]
 [2.36306672 2.16322831 1.41588616]
 [2.25262486 1.85295981 1.92461995]
 [0.49614614 0.38859019 1.85432239]
 [1.02704001 0.78912625 1.97450683]
 [2.12675745 1.45528949 2.60804545]]


In [4]:
mean_squared_error(A, A_estimate)

0.05134517953069396

In [5]:
mse = (np.square(A - A_estimate)).mean(axis=1)
mse

array([1.14841670e-01, 1.62074049e-03, 1.23847507e-02, 2.79700051e-02,
       1.34922594e-01, 1.70752340e-01, 2.73258735e-05, 3.22956034e-02,
       1.77180921e-02, 9.18674222e-04])